# Generated by Django 4.1.6 on 2023-02-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
